services:
  server:
    container_name: debug_test_api
    environment:
      - DB_NAME=quiz_db
      - DB_CONNECTION=mongodb://user:pass@db:27017
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: debug_test_db
    volumes:
      - "debug_test_db:/var/lib/mongodb/data"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_DATABASE=quiz_db
      - MONGO_INITDB_ROOT_PASSWORD=pass
volumes:
  debug_test_db:

