version: '3'
services:
  server:
    image: node:14
    working_dir: /server
    volumes:
      - type: bind
        source: ./server
        target: /server
  socket:
    image: node:14
    working_dir: /code
    volumes:
      - type: bind
        source: ./socketio
        target: /code  
  db:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - "dbdata:/var/lib/mongodb/data"
volumes:
  dbdata:


